language: java
jdk:
  - oraclejdk7
  - openjdk7

before_install:
  - wget -P $TRAVIS_BUILD_DIR/ https://cl.ly/lRLe/download/jrpg-2017a-dominio-0.1.jar
  - wget -P $TRAVIS_BUILD_DIR/ https://cl.ly/lRD0/download/jrpg-2017a-cliente-0.1.jar
